language: php

php:
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - sleep 60

script: php -f demo/wizzair.php BFS VNO 2016-11-21 2016-11-25
